---

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

bbb:
  hosts:
    bbb1.example.com:
    bbb2.example.com:
    bbb3.example.com:

  vars:
    #bbb_version: jammy-300
    #bbb_hostname: "{{ inventory_hostname }}"
    bbb_secret: CHANGE_MEEEEEE
    bbb_acme_enable: true
    bbb_acme_email: CHANGEME@example.com

    # Customizations...

    bbb_config_web:
      muteOnStart: true

    bbb_config_html5:
      public:
        app:
          mirrorOwnWebcam: true
          enableNetworkStats: true
          enableCopyNetworkStatsButton: true
        whiteboard:
          maxNumberOfAnnotations: 500


