---
- name: Read old bbb-web.properties
  become: true
  ansible.builtin.slurp:
    src: /etc/bigbluebutton/bbb-web.properties
  failed_when: false
  changed_when: false
  register: result

- name: Extract old BBB secret
  ansible.builtin.set_fact:
    bbb_old_secret: "{{ (result.content | default('') | b64decode | regex_search('securitySalt\\s*=\\s*(.+)', '\\1') or ['']) | first | trim }}"

- name: Check for running meetings
  when:
    - bbb_check_running
    - bbb_old_secret
  ansible.builtin.uri:
    url: https://{{ bbb_hostname }}/bigbluebutton/api/getMeetings?checksum={{ ('getMeetings' + bbb_old_secret) | hash('sha1') }}
    return_content: true
  register: meetings_result
  failed_when: false
  changed_when: false

- name: Fail if there are running meetings
  when:
    - bbb_check_running
    - bbb_old_secret
    - meetings_result.status | default(500) == 200
    - "'<messageKey>noMeetings</messageKey>' not in meetings_result.content"
  ansible.builtin.fail:
    msg: "There are running meetings on {{ bbb_hostname }} :/"
