---

- name: Delete freeswitch file logging config
  become: true
  file:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/logfile.conf.xml
    state: absent
  notify: Restart freeswitch

- name: Add freeswitch syslog config
  become: true
  template:
    src: freeswitch/syslog.conf.xml
    dest: /opt/freeswitch/etc/freeswitch/autoload_configs/syslog.conf.xml
    mode: "0644"
    owner: freeswitch
    group: daemon
  notify: Restart freeswitch

- name: Deploy conference config
  become: true
  template:
    src: freeswitch/conference.conf.xml
    dest: /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
    mode: "0644"
    owner: freeswitch
    group: daemon
  notify: Restart freeswitch

- name: Set socket password
  become: true
  community.general.xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
    xpath: /configuration/settings/param[@name='password']
    attribute: value
    value: "{{ bbb_freeswitch_socket_password }}"
  no_log: true
  notify: Restart freeswitch

- name: Set switch.conf loglevel
  become: true
  community.general.xml:
    path: /opt/freeswitch/etc/freeswitch/autoload_configs/switch.conf.xml
    xpath: /configuration/settings/param[@name='loglevel']
    attribute: value
    value: "{{ bbb_freeswitch_log_level }}"
  notify: Restart freeswitch

- name: Set freeswitch variables in vars.xml
  become: true
  ansible.builtin.lineinfile:
    path: /opt/freeswitch/etc/freeswitch/vars.xml
    regexp: "\\s+<X-PRE-PROCESS\\s+cmd=\"set\"\\s+data=\"{{item.name}}="
    line: "    <X-PRE-PROCESS cmd=\"set\" data=\"{{item.name}}={{item.value}}\" />"
    insertbefore: '</include>'
  loop:
    - {name: external_rtp_ip,   value: "{{bbb_freeswitch_external_ip}}"}
    - {name: external_sip_ip,   value: "{{bbb_freeswitch_external_ip}}"}
    - {name: default_password,  value: "{{bbb_freeswitch_default_password}}"}
    - {name: force_local_ip_v4, value: "{{bbb_freeswitch_local_ip}}"}
    - {name: local_ip_v4,       value: "$${force_local_ip_v4}"}
  notify: Restart freeswitch

- name: Set freeswitch external bind IP (v4)
  become: true
  community.general.xml:
    path: /opt/freeswitch/conf/sip_profiles/external.xml
    xpath: /profile/settings/param[@name='{{item.name}}']
    attribute: value
    value: "{{item.value}}"
  loop:
    - {name: ext-rtp-ip,  value: "$${external_rtp_ip}"}
    - {name: ext-sip-ip,  value: "$${external_sip_ip}"}
    - {name: sip-ip,      value: "$${external_sip_ip}"}
    - {name: rtp-ip,      value: "$${external_sip_ip}"}
    - {name: ws-binding,  value: "$${local_ip_v4}:5066"}
    - {name: wss-binding, value: "$${local_ip_v4}:7443"}
  notify: Restart freeswitch

- name: Set restrictive permissions of freeswitch config files including passwords
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: freeswitch
    group: daemon
    mode: "0600"
  with_items:
    - /opt/freeswitch/etc/freeswitch/vars.xml
    - /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml

- name: Configure IPv6-Support in freeswitch
  become: true
  block:
    - name: Configure listen-ip in event_socket.conf.xml
      community.general.xml:
        path: /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
        xpath: /configuration/settings/param[@name="listen-ip"]
        attribute: value
        value: "{{ '::' if bbb_freeswitch_ipv6 | bool else '127.0.0.1' }}"
      notify: Restart freeswitch

    - name: Stat ipv6 sip_profiles
      ansible.builtin.stat:
        path: "{{ item + '.disabled' if bbb_freeswitch_ipv6 | bool else item }}"
      register: ipv6_sip_profiles
      loop:
        - /opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml
        - /opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml
      loop_control:
        label: "{{ item if bbb_freeswitch_ipv6 | bool else item + '.disabled' }}"

    - name: Manage ipv6 sip_profiles
      command: >
        mv
          "{{ sip_profile.item + '.disabled' if bbb_freeswitch_ipv6 | bool else sip_profile.item }}"
          "{{ sip_profile.item if bbb_freeswitch_ipv6 | bool else sip_profile.item + '.disabled' }}"
      when: sip_profile.stat.exists
      loop: "{{ ipv6_sip_profiles.results }}"
      loop_control:
        loop_var: sip_profile
        label: "{{ sip_profile.item if bbb_freeswitch_ipv6 | bool else sip_profile.item + '.disabled' }}"
      notify: Restart freeswitch

- name: FreeSWITCH dialplan quality
  become: true
  replace:
    path: /opt/freeswitch/conf/dialplan/default/bbb_conference.xml
    regexp: <action application="conference" data="\$1@.*"\/>
    replace: <action application="conference" data="$1@{{ bbb_dialplan_quality }}"/>
  notify: Restart freeswitch

- name: FreeSWITCH dialplan quality (echo)
  become: true
  replace:
    path: /opt/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
    regexp: <action application="conference" data="\${vbridge}@.*"\/>
    replace: <action application="conference" data="${vbridge}@{{ bbb_dialplan_quality }}"/>
  notify: Restart freeswitch

- name: Fix fs_clibbb to accept additional parameters
  become: true
  lineinfile:
    path: /usr/local/bin/fs_clibbb
    regexp: ^/opt/freeswitch/bin/fs_cli
    line: /opt/freeswitch/bin/fs_cli -p $(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)
      "$@"


- name: Configure different mute sound
  become: true
  copy:
    src: sounds/{{ item }}/conf-muted.wav
    dest: /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/{{ item }}/
    mode: "0644"
    owner: freeswitch
    group: daemon
  with_items:
    - 48000
    - 32000
    - 16000
    - 8000
  when: bbb_freeswitch_muted_sound | bool

- name: Configure different unmute sound
  become: true
  copy:
    src: sounds/{{ item }}/conf-unmuted.wav
    dest: /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/{{ item }}/
    mode: "0644"
    owner: freeswitch
    group: daemon
  with_items:
    - 48000
    - 32000
    - 16000
    - 8000
  when: bbb_freeswitch_muted_sound | bool
