---

- name: Deploy dial-in config files
  become: true
  when: bbb_dialin_enable
  ansible.builtin.template:
    src: "dial-in/{{ item.src }}.j2"
    dest: "/opt/freeswitch/conf/{{ item.dest }}"
    owner: freeswitch
    group: daemon
    mode: "0644"
  loop: &configfiles
    - src: provider.xml
      dest: sip_profiles/external/dial-in.xml
    - src: dialplan.xml
      dest: dialplan/public/dial-in.xml
  notify: Restart freeswitch

- name: Remove unused dial-in config files
  become: true
  when: not bbb_dialin_enable
  ansible.builtin.file:
    path: "/opt/freeswitch/conf/{{ item.dest }}"
    state: absent
  loop: *configfiles
  notify: Restart freeswitch

