---
- name: Ensure pip and docker-compose-plugin is installed
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - docker-compose-plugin
    state: "{{ bbb_state }}"

- name: Install python docker packages
  pip:
    name:
      - docker
      - docker-compose=={{ bbb_docker_compose_version }}
    state: "{{ bbb_state }}"

- name: Configure docker daemon
  become: true
  ansible.builtin.template:
    src: "docker/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: '0600'
  when: "bbb_docker_config | default(False)"
  notify: Reload docker

- name: Log into DockerHub (avoid rate limits)
  become: true
  community.docker.docker_login:
    username: "{{ bbb_docker_user }}"
    password: "{{ bbb_docker_passwd }}"
  no_log: true
  when: bbb_docker_user|default(None) and bbb_docker_passwd|default(None)
