---
- name: Refresh apt caches
  become: true
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install system dependencies
  become: true
  ansible.builtin.package:
    name: "{{ bbb_packages_system }}"
    state: present

- name: Set local hostname to match bbb_hostname
  become: true
  hostname:
    name: "{{ bbb_hostname }}"
    use: systemd

- name: Generate locales
  become: true
  community.general.locale_gen:
    name: "{{ bbb_system_locale }}"
    state: present

- name: Check current locale
  command: localectl status
  changed_when: false
  register: locale_status

- name: Ensure locale is set correctly
  become: true
  ansible.builtin.command:
    cmd: "localectl set-locale LANG={{ bbb_system_locale }}"
  when: "('System Locale: LANG=' + bbb_system_locale) not in locale_status.stdout"

- name: Set default java version
  become: true
  ansible.builtin.file:
    src: /usr/lib/jvm/java-{{ bbb_java_version }}-openjdk-amd64/bin/java
    dest: /etc/alternatives/java
    state: link

- name: Download PGP Keys for extra repositories
  become: true
  ansible.builtin.get_url:
    url: "{{ item.key }}"
    dest: "/etc/apt/keyrings/{{ item.name }}.asc"
    mode: "0644"
  loop: "{{ bbb_package_repos }}"
  when: "item.key | default(False)"

- name: Configure extra repositories
  become: true
  ansible.builtin.apt_repository:
    filename: "{{ item.name }}"
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ bbb_package_repos }}"
  register: result

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    upgrade: "yes"
  when: bbb_upgrade
  notify: Restart bigbluebutton