---
# Sanity and pre-run checks
- import_tasks: check-vars.yml
  tags: ["always", "checks"]
- import_tasks: check-running.yml
  tags: ["always", "checks"]

# Tighten Firewall before install
- import_tasks: firewall/enable.yml
  when: bbb_ufw_enable
  tags: ["firewall"]
- import_tasks: firewall/disable.yml
  when: not bbb_ufw_enable
  tags: ["firewall"]

# Install or upgrade packages
- import_tasks: install-base.yml
  tags: ["install"]
- import_tasks: install-docker.yml
  tags: ["install"]
- import_tasks: install-bbb.yml
  tags: ["install"]
- import_tasks: install-scripts.yml
  tags: ["install"]

# Certificates
- import_tasks: certs.yml
  tags: ["certs"]

# Configuration mixins and features
- import_tasks: mixin-proxy.yml
  when: "bbb_cluster_proxy is defined"
- import_tasks: mixin-backgrounds.yml

# Deploy configuration
- import_tasks: configure-bbb.yml
  tags: ["configure"]
- import_tasks: configure-freeswitch.yml
  tags: ["configure"]
- import_tasks: configure-dialin.yml
  tags: ["configure"]
- import_tasks: configure-nginx.yml
  tags: ["configure"]
- import_tasks: configure-misc.yml
  tags: ["configure"]

- name: Flush Handler
  meta: flush_handlers
