---
# TODO: Cache buster? really necessary?

- name: Deploy custom.css
  become: true
  copy:
    dest: "{{ bbb_nginx_root }}/custom.css"
    content: "{{ bbb_html5_style if ';' in bbb_html5_style else lookup('ansible.builtin.file', bbb_html5_style) }}"
    mode: "0644"
    owner: bigbluebutton
    group: bigbluebutton
  when: "bbb_html5_style is defined"

- name: Configure html5 client to use custom.css by default
  set_fact:
    bbb_config_html5_base: |
      {{ bbb_config_html5_base | combine({
         'public': {
            'app': {
               'customStyleUrl': 'https://'+bbb_hostname+'/custom.css'
            }
          }
        }, recursive=True) }}
  when: "bbb_html5_style is defined"
