---
- name: Reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: Reload nginx
  become: true
  systemd:
    name: nginx
    state: reloaded

- name: Restart nginx
  become: true
  systemd:
    name: nginx
    state: restarted

- name: Reload docker
  become: true
  systemd:
    name: docker
    state: reloaded

- name: Restart freeswitch
  become: true
  systemd:
    name: freeswitch
    state: restarted

- name: Restart bigbluebutton
  become: true
  command: bbb-conf --restart
