---
- name: Converge
  hosts: bbb
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    bbb_acme_enable: false
    bbb_acme_email: mail@example.com
  tasks:
    - name: "Include ebbba.bigbluebutton"
      include_role:
        name: "ebbba.bigbluebutton"
